module.exports = {
  QUIT: "QUIT",
  CONNECT: "CONNECT",
  DISCONNECT: "DISCONNECT",
  UPDATE_OPTIONS: "UPDATE_OPTIONS",
  CHECK_FOR_UPDATES: "CHECK_FOR_UPDATES",
  DISCORD_CONNECTING: "DISCORD_CONNECTING",
  DISCORD_READY: "DISCORD_READY",
  DISCORD_DISCONNECTED: "DISCORD_DISCONNECTED",
  DISCORD_LOGIN_ERROR: "DISCORD_LOGIN_ERROR",
};
